# Generated by Django 4.2.5 on 2023-09-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=30)),
                (
                    "property_type",
                    models.CharField(
                        choices=[("rent", "Rental"), ("buy", "Buy"), ("sale", "Sale")],
                        max_length=10,
                    ),
                ),
                ("location_pincode", models.CharField(max_length=10)),
                ("location_city", models.CharField(max_length=50)),
                ("location_area", models.CharField(max_length=50)),
                ("landmark", models.CharField(max_length=100)),
                ("owner_or_agent", models.BooleanField(default=True)),
                (
                    "photos",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_photos/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="property_videos/"
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("summary", models.TextField()),
                (
                    "rent_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("owner_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "owner_id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="owner_documents/"
                    ),
                ),
                (
                    "property_type_buy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Flat"),
                            ("land", "Land for sale"),
                            ("office", "Office for Sale"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "property_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="property_documents/"
                    ),
                ),
                ("owner_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_photos/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.property"
                    ),
                ),
            ],
            options={
                "ordering": ["property", "order"],
            },
        ),
    ]
